manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: theitroma
      url-base: https://github.com/TheItroma
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: tonato_module
      remote: theitroma
      revision: main
  self:
    path: config
